"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$directory\
[](bg:pink fg:surface0)\
$git_branch\
$git_status\
[](bg:sky fg:pink)\
$nodejs\
$golang\
[](bg:blue fg:sky)\
$kubernetes\
[](fg:blue)
$character\
"""

palette = 'catppuccin_mocha'

[directory]
style = 'bg:surface0'
format = '[$path ]($style)[$read_only]($style)'
read_only = '🔒 '

[git_branch]
format = '[ $symbol$branch]($style)'
style = 'bg:pink fg:surface0'

[git_status]
format = '[ $all_status$ahead_behind ]($style)'
style = 'bg:pink fg:surface0'

[nodejs]
disabled = false
format = '[ $symbol$version ](bg:sky fg:surface0)'
detect_files = ['package.json']

[golang]
disabled = false
symbol = " "
format = '[ $symbol$version ]($style)'
detect_folders = ['Godeps']
style = 'bg:sky fg:surface0'

[kubernetes]
disabled = false
format = '[ $symbol$context ]($style)'
style = 'bg:blue fg:surface0'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
